# Generated by Django 4.0.4 on 2022-05-24 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookJournalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.bookjournalbase')),
                ('num_pages', models.IntegerField()),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'horror'), (2, 'fantasy'), (3, 'scientific'), (4, 'adventure'), (5, 'biography')])),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('id',),
            },
            bases=('book.bookjournalbase',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('bookjournalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.bookjournalbase')),
                ('publisher', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'bullet'), (2, 'food'), (3, 'travel'), (4, 'sport')])),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ('id',),
            },
            bases=('book.bookjournalbase',),
        ),
    ]
