# Generated by Django 4.0.4 on 2022-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'horror'), (2, 'fantasy'), (3, 'scientific'), (4, 'adventure'), (5, 'biography')], default=2),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bullet'), (2, 'food'), (3, 'travel'), (4, 'sport')], default=4),
        ),
    ]
