# Generated by Django 4.0.4 on 2022-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_genre_alter_journal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('roles', models.PositiveSmallIntegerField(choices=[(1, 'super admin'), (2, 'guest')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
